apiVersion: v1
kind: Service
metadata:
  name: glance-service
  labels:
    app: glance
  namespace: glance
spec:
  selector:
    app: glance
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: glance-port
  type: ClusterIP
