apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-secret
  namespace: cloudflared
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiM2MwM2Q4MGYxNWFmYTE3OGYyYmM4MTEwZGRmZGQ4NzIiLCJUdW5uZWxTZWNyZXQiOiJDYXNnKzVDU1NmY1grTnhnRmQvbUFTTmZlekhQK1ZqM1JNcU4vSzBxYVVjPSIsIlR1bm5lbElEIjoiOTdkNTI1NGItM2RjZS00ZDFiLWJiOTctZDAzYjAyNDlhMmY3IiwiRW5kcG9pbnQiOiIifQ==
