---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgBRfdaxUDslrUgahUP/RNdO0ICzHorkYDEildcj+Mh5tzqRW97m2p9tXmJ4JMLQ4sUDDJgmFKyCQKXzX73AahyYgYdFxH4fNztbbnpnQTH3pCxdsZ3Up+sTy4KST/0yE3cWLQls2vZGfn/NYPeHrKU4PRBPDgM/uWc/KjtlpAfgM1djbaKzO22zl+wq0pdvv26HFrG59FBDQNhujgbKdngKYXb6iFIIk+B+4EzqKS5NRPuxkTevKrHSYphnLEaDZyORG8io8cNeQxyjC+8PeoDNyh1Q+Hv9Eb7cllS2SbuIwPkNy2fBucDy4hvdK4TBAKA7kcbPnHcqYRs83wgsWdYYRDnpbE3jjnJ8f+akesKBfpOqm9g0CSKRDj42ettVtFCx2CiQJ7KN/3S0INwTuooHx9vcv2P9cVtE0H+c3EB2YujOmy62ZI4juDBovL9kxeOvbvumNVaNADnAd0dUZ43fkjQGAHNXYzZhWYQeS99yfzMb77StwPkAsGOtc4j2nCnkzRv0RaM0NE0iMuLpf+/DhkKf6k5IJXfi+hfAeCBx4DGhfwPX2kGKkflupxC4EziTLSP5kVeoLbHrbw7QgTpBW4ZKEFxREoODmDZpf3A8GJQPhs17dArWAhXXKLnn5re7QL5rv+7Bd7tyFSGSQyoejVhx2eL0Sw4AqJt122qDKW6801KGyw3T9qnkZ9lcmBD8TSj5wiGh+cnpf2jyMWd/bllxdMVKT3muqaEaSdiKQmKLBr0iblYcWjgu3mgcgRbP/eX577LCsQsLEqtb4H6Trjj+5k7+b2g0HNyKD4WcoFkHcv0llEPSJLbR42F+McE6wE4MgKPbP4xZ4yJdmSHEwHfTGf9VNwpX
  template:
    metadata:
      name: discord-webhook
      namespace: monitoring
    type: Opaque
