apiVersion: v1
kind: Service
metadata:
  name: hugo-blog-service
  namespace: default
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-blog
  type: ClusterIP
