apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-blog-deployment
  namespace: default
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: hugo-blog
          image: ghcr.io/pflorov/devops-blog:94b39d954cf719c497f3875d76eadbd8f9f65c85
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
