apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:

  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - 'alertmanager.monitoring.svc.cluster.local:9093'

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__address__]
            regex: '(.+):(\d+)'
            replacement: '${1}:10250'
            target_label: __address__
          - target_label: __metrics_path__
            replacement: /metrics/cadvisor

      - job_name: 'kubernetes-node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            regex: 'node-exporter;metrics'
            action: keep
          - source_labels: [__address__]
            target_label: instance
            regex: '(.+)'
            replacement: '$1'
          - target_label: __metrics_path__
            replacement: /metrics
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
