apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      initContainers:
        - name: render-config
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              WEBHOOK_URL="$(cat /secrets/webhook-url)"
              sed "s|__DISCORD_WEBHOOK_URL__|${WEBHOOK_URL}|g" \
                /config-template/config.yml.tmpl \
                > /etc/alertmanager/config.yml
          volumeMounts:
            - name: config-template-volume
              mountPath: /config-template
              readOnly: true
            - name: discord-secret-volume
              mountPath: /secrets
              readOnly: true
            - name: rendered-config-volume
              mountPath: /etc/alertmanager

      containers:
        - name: alertmanager
          image: quay.io/prometheus/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/config.yml"
            - "--storage.path=/alertmanager"
          ports:
            - name: web
              containerPort: 9093
              hostPort: 9093
          volumeMounts:
            - name: rendered-config-volume
              mountPath: /etc/alertmanager
            - name: storage
              mountPath: /alertmanager
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: config-template-volume
          configMap:
            name: alertmanager-config-template
        - name: discord-secret-volume
          secret:
            secretName: discord-webhook
        - name: rendered-config-volume
          emptyDir: {}
        - name: storage
          emptyDir: {}
