apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
  labels:
    app: cloudflared-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: cloudflared-tunnel
        image: cloudflare/cloudflared:2025.8.1
        args:
          - tunnel
          - --config
          - /etc/cloudflared/config.yaml
          - run
          - k3s-ingress-tunnel
        volumeMounts:
          - name: config
            mountPath: /etc/cloudflared/config.yaml
            subPath: config.yaml
          - name: credentials
            mountPath: /etc/cloudflared/credentials.json
            subPath: credentials.json
          - name: origin-cert
            mountPath: /etc/cloudflared/cert.pem
            subPath: tls.crt
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
        - name: credentials
          secret:
            secretName: cloudflared-tunnel-secret
        - name: origin-cert
          secret:
            secretName: cloudflared-origin-cert
